# Generated by Django 3.2.7 on 2021-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0002_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
