# Generated by Django 3.2.7 on 2021-10-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('minPrice', models.FloatField(default=0)),
                ('grams', models.FloatField(default=0)),
                ('amorNew', models.FloatField(default=0)),
                ('amorRep', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('isPrinting', models.BooleanField(default=False)),
                ('mermaFix', models.FloatField(default=0)),
                ('mermaVar', models.FloatField(default=0)),
                ('setupTime', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('machine', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs_controller.processcategory')),
                ('costs', models.ManyToManyField(to='costs_controller.Cost')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs_controller.unit')),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs_controller.costcategory'),
        ),
        migrations.AddField(
            model_name='cost',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs_controller.unit'),
        ),
    ]
