# Generated by Django 3.2.7 on 2021-10-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='costs_controller.costcategory'),
        ),
    ]
